name: lescavesduroussillon
description: "Les Caves du Roussillon"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  get:
  get_storage:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_fonts:

  infinite_carousel:
  auto_size_text:
  url_launcher: ^6.2.6
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true
