name: lescavesduroussillon
description: "Les Caves du Roussillon"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  get:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_fonts:

  infinite_carousel:
  auto_size_text:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true